from typing import Annotated, Sequence, TypedDict, List, Optional
from langchain_core.messages import BaseMessage
import operator

class AgentState(TypedDict):
    """
    Shared memory schema for the multi-agent system.
    """
    # Messages list uses operator.add so new messages are appended rather than overwriting
    messages: Annotated[Sequence[BaseMessage], operator.add]
    
    # Target node for the supervisor's next routing decision
    next_step: str
    
    # Original user goal/prompt
    user_goal: str
    
    # Dynamic plan generated by the supervisor
    plan: List[str]
    
    # Structured outputs collected from worker agents
    research_data: Optional[str]
    code_output: Optional[str]
    review_feedback: Optional[str]
    
    # Self-correction cycle counter to prevent infinite loops
    iteration_count: int
    
    # Final synthesized answer ready for delivery
    final_output: Optional[str]